spring:
  profiles:
    include:
      - db
      - auth
    active: local
wisemil:
  security:
    mode: stub

---
spring:
  profiles: test
---
spring:
  profiles: local
wisemil:
  security:
    mode: oauth
---
spring:
  profiles: prod
wisemil:
  security:
    mode: oauth
