spring:
  profiles:
    include:
      - db
      - auth
      - jwt
    active: local
wisemeal:
  security:
    mode: stub

---
spring:
  profiles: test
---
spring:
  profiles: local
wisemeal:
  security:
    mode: oauth
---
spring:
  profiles: prod
wisemeal:
  security:
    mode: oauth
