spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
      hibernate.default_batch_fetch_size: ${chunkSize:1000}
      hibernate.connection.provider_disables_autocommit: true
      hibernate.jdbc.batch_size: ${chunkSize:1000}
      hibernate.order_inserts: true
      hibernate.order_updates: true
    open-in-view: false
  flyway:
    enabled: false
  profiles:
    include: db-prod
---
spring:
  profiles: test
  h2:
    console.enabled: true
    console.path: /h2-console
  jpa:
    database-platform: H2
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem://localhost/~/wisemeal;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    hikari:
      connectionTimeout: 3000
      max-lifetime: 58000  # 58s
      maximumPoolSize: 10
      data-source-properties:
        connectTimeout: 2000
        socketTimeout: 60000
      auto-commit: false

---
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:6021/wisemeal?useSSL=false
    username: wisemeal_app
    password: wisemeal_app
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      connectionTimeout: 3000
      max-lifetime: 58000  # 58s
      maximumPoolSize: 10
      data-source-properties:
        connectTimeout: 2000
        socketTimeout: 60000
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
logging:
  level:
    org:
      hibernate:
        type: TRACE
