name: System Deploy

on:
  workflow_dispatch:
    inputs:
      targetSystem:
        description: '배포 대상'
        type: choice
        required: true
        options:
          - wisemeal-api
          - wisemeal-batch

env:
  DEPLOY_DIR: ./deploy
  TARGET_SYSTEM: ${{ github.event.inputs.targetSystem }}

jobs:
  Deploy-Application:
    runs-on: ubuntu-latest
    steps:
      - name: Check out to ${{ github.ref }}
        uses: actions/checkout@v3
#        with:
#          token: ${{ secrets.BACK_SECRET }}
#          submodules: true

      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Build Artifact
        run: |
          ./gradlew clean :$TARGET_SYSTEM:test
          ./gradlew clean :$TARGET_SYSTEM:integrationTest
          ./gradlew clean :$TARGET_SYSTEM:build -x test

      - name: Zip Artifact
        run: |
          mkdir -p ./deploy
          cp ./$TARGET_SYSTEM/build/libs/*.jar $DEPLOY_DIR
          cp ./$TARGET_SYSTEM/appspec/* $DEPLOY_DIR
          zip -r $DEPLOY_DIR/application.zip $DEPLOY_DIR/*

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_CODE_DEPLOY_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_CODE_DEPLOY_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload JAR to AWS S3
        run: aws s3 cp --region ap-northeast-2 --acl private $DEPLOY_DIR/application.zip s3://pci-private/deploy/$TARGET_SYSTEM

#      - name: Deploy Application
#        run : |
#          echo 'deploy by AWS CodeDeploy'
#          echo 'remove deploy directory'
#          rm -rf $DEPLOY_DIR
